name: pyqmmm
channels:
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.8
  - ambertools
  - black
  - cookiecutter
  - click
  - matplotlib
  - modeller
  - numpy
  - pandas
  - pip
  - plotly
  - scipy
  - seaborn
  - sphinx
  - sphinx-autoapi
  - sphinx_rtd_theme
  - xtb
  - crest
  - pip:
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip
