name: caddkit
channels:
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.8
  - ambertools
  - biopandas
  - click
  - matplotlib
  - mdanalysis
  - numpy
  - pandas
  - pip
  - plotly
  - scipy
  - seaborn
  - xtb
  - crest

