name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - matplotlib
  - pandas

  #   # Pip-only installs
  # - pip:
  #   - sphinx-autoapi
  #   - numpydoc