name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Pip-only installs
  - pip:
    - sphinx-autoapi==3.0.0
    - sphinx==6.2.1
    - numpy
    - matplotlib
    - modeller
    - pandas
    - plotly
    - seaborn
    - scipy
    - https://github.com/revitron/revitron-sphinx-theme/archive/refs/tags/0.7.0.zip


